// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHKjXvjsVshxMEHTk1dlEV0zlfkxVS8lo',
    appId: '1:260070046054:web:bf392f91e1d13e8c5230a7',
    messagingSenderId: '260070046054',
    projectId: 'star-book-7db0e',
    authDomain: 'star-book-7db0e.firebaseapp.com',
    storageBucket: 'star-book-7db0e.appspot.com',
    measurementId: 'G-75RGVXNEJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoFHwzJn9pZb-7MXAJUwnlKpsE0N6jZz0',
    appId: '1:260070046054:android:48cb67f9142ff84b5230a7',
    messagingSenderId: '260070046054',
    projectId: 'star-book-7db0e',
    storageBucket: 'star-book-7db0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ZyhpkgSSsyqA5NvOvKArLGXdWkfYP2o',
    appId: '1:260070046054:ios:ee530cee958a7fd55230a7',
    messagingSenderId: '260070046054',
    projectId: 'star-book-7db0e',
    storageBucket: 'star-book-7db0e.appspot.com',
    iosBundleId: 'com.example.flutterUtilHub',
  );
}
